FROM ubuntu:16.04

RUN apt update && \
    apt install -y \
    wget \
    git \
    net-tools \
    htop \
    bmon \
    vim

WORKDIR /root

RUN wget https://s3-eu-west-1.amazonaws.com/ur-support-site/168410/URSim_Linux-5.12.2.1101534.tar.gz

RUN tar -xvf URSim_Linux-5.12.2.1101534.tar.gz

#install ur specific dependecies
RUN apt install -y \
      openjdk-8-jdk \
      policykit-1 \
      xterm \
      libjava3d-java \
      psmisc \
      iputils-ping


RUN wget https://raw.githubusercontent.com/ljden/URSim_Install_Guides/main/src/net-statistics && \
    mv net-statistics /sbin/ && \
    chmod +x /sbin/net-statistics

RUN echo -e "\nPATH=$PATH:$HOME/ursim-5.12.2.1101534/usr/bin" >> /root/.profile

# todo rename extracted folder

WORKDIR /root/ursim-5.12.2.1101534

RUN mkdir /root/Desktop && \
    sed -i 's|xterm |#xterm|g' ./install.sh


RUN sed -i 's|pkexec ||g' ./install.sh && \
    sed -i 's|sudo ||g' ./install.sh && \
    ./install.sh
